server:
  port: 8080

spring:
  application:
    name: comline-edge

comline:
  api:
    base-url: ${COMLINE_BASE_URL:https://ctofinder.comline-shop.de/4DCGI/direct}
    mid: 219
    action: getCTOConf
    customerNumber: ${COMLINE_CUSTOMER_NUMBER:15017319}
    password: ${COMLINE_PASSWORD:fM6v62eNoBSL}

# Actuator configuration for metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    de.conrad.ccp.comline: DEBUG
    org.springframework.web: INFO
